var searchData=
[
  ['_3a_20condition_20to_20enable_20error_20bounding_20box_20computation_0',[': condition to enable error bounding box computation',['../POD__application__example__00001_8cpp.html#autotoc_md22',1,'&lt;B&gt;doBoundingBox&lt;/B&gt;: condition to enable error bounding box computation'],['../POD__application__example__00001_8cpp.html#autotoc_md73',1,'&lt;B&gt;doBoundingBox&lt;/B&gt;: condition to enable error bounding box computation']]],
  ['_3a_20condition_20to_20enable_20error_20map_20computation_20through_20leave_201_20out_1',[': condition to enable error map computation through leave 1 out',['../POD__application__example__00001_8cpp.html#autotoc_md21',1,'&lt;B&gt;doLeave1out&lt;/B&gt;: condition to enable error map computation through leave-1-out'],['../POD__application__example__00001_8cpp.html#autotoc_md72',1,'&lt;B&gt;doLeave1out&lt;/B&gt;: condition to enable error map computation through leave-1-out']]],
  ['_3a_20condition_20to_20enable_20whole_20pod_20basis_20computation_2',[': condition to enable whole POD basis computation',['../POD__application__example__00001_8cpp.html#autotoc_md20',1,'&lt;B&gt;doPODbasis&lt;/B&gt;: condition to enable whole POD basis computation'],['../POD__application__example__00001_8cpp.html#autotoc_md71',1,'&lt;B&gt;doPODbasis&lt;/B&gt;: condition to enable whole POD basis computation']]],
  ['_3a_20condition_20to_20set_20if_20the_20mesh_20of_20the_20database_20snapshots_20is_20the_20same_20or_20not_3',[': condition to set if the mesh of the database snapshots is the same or not',['../POD__application__example__00001_8cpp.html#autotoc_md9',1,'&lt;B&gt;StaticMesh&lt;/B&gt;: condition to set if the mesh of the database snapshots is the same or not'],['../POD__application__example__00001_8cpp.html#autotoc_md42',1,'&lt;B&gt;StaticMesh&lt;/B&gt;: condition to set if the mesh of the database snapshots is the same or not']]],
  ['_3a_20condition_20to_20unset_20if_20the_20mean_20is_20not_20computed_4',[': condition to unset if the mean is not computed',['../POD__application__example__00001_8cpp.html#autotoc_md14',1,'&lt;B&gt;Mean&lt;/B&gt;: condition to unset if the mean is not computed'],['../POD__application__example__00001_8cpp.html#autotoc_md47',1,'&lt;B&gt;Mean&lt;/B&gt;: condition to unset if the mean is not computed']]],
  ['_3a_20error_20mode_20of_20the_20pod_20object_5',[': error mode of the pod object',['../POD__application__example__00001_8cpp.html#autotoc_md7',1,'&lt;B&gt;ErrorMode&lt;/B&gt;: error mode of the pod object'],['../POD__application__example__00001_8cpp.html#autotoc_md40',1,'&lt;B&gt;ErrorMode&lt;/B&gt;: error mode of the pod object']]],
  ['_3a_20execute_20mode_20of_20the_20pod_20object_6',[': execute mode of the pod object',['../POD__application__example__00001_8cpp.html#autotoc_md4',1,'&lt;B&gt;RunMode&lt;/B&gt;: execute mode of the pod object'],['../POD__application__example__00001_8cpp.html#autotoc_md37',1,'&lt;B&gt;RunMode&lt;/B&gt;: execute mode of the pod object']]],
  ['_3a_20folder_20where_20the_20pod_20dumping_20files_20and_20results_20are_20written_7',[': folder where the pod dumping files and results are written',['../POD__application__example__00001_8cpp.html#autotoc_md1',1,'&lt;B&gt;Directory&lt;/B&gt;: folder where the pod dumping files and results are written'],['../POD__application__example__00001_8cpp.html#autotoc_md34',1,'&lt;B&gt;Directory&lt;/B&gt;: folder where the pod dumping files and results are written']]],
  ['_3a_20memory_20mode_20of_20the_20pod_20object_8',[': memory mode of the pod object',['../POD__application__example__00001_8cpp.html#autotoc_md3',1,'&lt;B&gt;MemoryMode&lt;/B&gt;: memory mode of the pod object'],['../POD__application__example__00001_8cpp.html#autotoc_md36',1,'&lt;B&gt;MemoryMode&lt;/B&gt;: memory mode of the pod object']]],
  ['_3a_20mesh_20type_20of_20the_20pod_20object_20b_20meshtype_20b_9',[': mesh type of the pod object B MeshType B',['../POD__application__example__00001_8cpp.html#autotoc_md8',1,'&lt;B&gt;MeshType&lt;/B&gt;: mesh type of the pod object&lt;B&gt;/MeshType&lt;/B&gt;'],['../POD__application__example__00001_8cpp.html#autotoc_md41',1,'&lt;B&gt;MeshType&lt;/B&gt;: mesh type of the pod object&lt;B&gt;/MeshType&lt;/B&gt;']]],
  ['_3a_20name_20of_20the_20snapshot_20file_20used_20to_20read_20the_20pod_20mesh_20b_20meshname_20b_10',[': name of the snapshot file used to read the pod mesh B MeshName B',['../POD__application__example__00001_8cpp.html#autotoc_md11',1,'&lt;B&gt;MeshName&lt;/B&gt;: name of the snapshot file used to read the pod mesh&lt;B&gt;/MeshName&lt;/B&gt;'],['../POD__application__example__00001_8cpp.html#autotoc_md44',1,'&lt;B&gt;MeshName&lt;/B&gt;: name of the snapshot file used to read the pod mesh&lt;B&gt;/MeshName&lt;/B&gt;']]],
  ['_3a_20path_20of_20the_20snapshot_20file_20used_20to_20read_20the_20pod_20mesh_20b_20meshdirectory_20b_11',[': path of the snapshot file used to read the pod mesh B MeshDirectory B',['../POD__application__example__00001_8cpp.html#autotoc_md10',1,'&lt;B&gt;MeshDirectory&lt;/B&gt;: path of the snapshot file used to read the pod mesh&lt;B&gt;/MeshDirectory&lt;/B&gt;'],['../POD__application__example__00001_8cpp.html#autotoc_md43',1,'&lt;B&gt;MeshDirectory&lt;/B&gt;: path of the snapshot file used to read the pod mesh&lt;B&gt;/MeshDirectory&lt;/B&gt;']]],
  ['_3a_20reconstruction_20mode_20of_20the_20pod_20object_12',[': reconstruction mode of the pod object',['../POD__application__example__00001_8cpp.html#autotoc_md6',1,'&lt;B&gt;ReconstructionMode&lt;/B&gt;: reconstruction mode of the pod object'],['../POD__application__example__00001_8cpp.html#autotoc_md39',1,'&lt;B&gt;ReconstructionMode&lt;/B&gt;: reconstruction mode of the pod object']]],
  ['_3a_20specific_20name_20identifying_20the_20pod_20case_13',[': specific name identifying the pod case',['../POD__application__example__00001_8cpp.html#autotoc_md2',1,'&lt;B&gt;Name&lt;/B&gt;: specific name identifying the pod case'],['../POD__application__example__00001_8cpp.html#autotoc_md35',1,'&lt;B&gt;Name&lt;/B&gt;: specific name identifying the pod case']]],
  ['_3a_20target_20energy_20level_20to_20set_20the_20number_20of_20retained_20modes_20minimum_20between_20desired_20n_20modes_20and_20energy_20level_14',[': target energy level to set the number of retained modes minimum between desired n modes and energy level',['../POD__application__example__00001_8cpp.html#autotoc_md13',1,'&lt;B&gt;Energy&lt;/B&gt;: target energy level to set the number of retained modes (minimum between desired n modes and energy level)'],['../POD__application__example__00001_8cpp.html#autotoc_md46',1,'&lt;B&gt;Energy&lt;/B&gt;: target energy level to set the number of retained modes (minimum between desired n modes and energy level)']]],
  ['_3a_20target_20error_20threshold_20to_20define_20the_20error_20map_20bounding_20box_15',[': target error threshold to define the error map bounding box',['../POD__application__example__00001_8cpp.html#autotoc_md15',1,'&lt;B&gt;ErrorThreshold&lt;/B&gt;: target error threshold to define the error map bounding box'],['../POD__application__example__00001_8cpp.html#autotoc_md48',1,'&lt;B&gt;ErrorThreshold&lt;/B&gt;: target error threshold to define the error map bounding box']]],
  ['_3a_20target_20number_20of_20retained_20modes_20minimum_20between_20desired_20n_20modes_20and_20energy_20level_16',[': target number of retained modes minimum between desired n modes and energy level',['../POD__application__example__00001_8cpp.html#autotoc_md12',1,'&lt;B&gt;Modes&lt;/B&gt;: target number of retained modes (minimum between desired n modes and energy level)'],['../POD__application__example__00001_8cpp.html#autotoc_md45',1,'&lt;B&gt;Modes&lt;/B&gt;: target number of retained modes (minimum between desired n modes and energy level)']]],
  ['_3a_20target_20scalar_20fields_20to_20be_20used_20in_20error_20bounding_20box_20evaluation_17',[': target scalar fields to be used in error bounding box evaluation',['../POD__application__example__00001_8cpp.html#autotoc_md16',1,'&lt;B&gt;ErrorScalarFields&lt;/B&gt;: target scalar fields to be used in error bounding box evaluation'],['../POD__application__example__00001_8cpp.html#autotoc_md49',1,'&lt;B&gt;ErrorScalarFields&lt;/B&gt;: target scalar fields to be used in error bounding box evaluation']]],
  ['_3a_20target_20vector_20fields_20to_20be_20used_20in_20error_20bounding_20box_20evaluation_18',[': target vector fields to be used in error bounding box evaluation',['../POD__application__example__00001_8cpp.html#autotoc_md17',1,'&lt;B&gt;ErrorVectorFields&lt;/B&gt;: target vector fields to be used in error bounding box evaluation'],['../POD__application__example__00001_8cpp.html#autotoc_md50',1,'&lt;B&gt;ErrorVectorFields&lt;/B&gt;: target vector fields to be used in error bounding box evaluation']]],
  ['_3a_20write_20mode_20of_20the_20pod_20object_19',[': write mode of the pod object',['../POD__application__example__00001_8cpp.html#autotoc_md5',1,'&lt;B&gt;WriteMode&lt;/B&gt;: write mode of the pod object'],['../POD__application__example__00001_8cpp.html#autotoc_md38',1,'&lt;B&gt;WriteMode&lt;/B&gt;: write mode of the pod object']]]
];
